language: python
python:
    - "2.7"
install:
  - pip install pytest
  - pip install coveralls
  - pip install pytest-cov
  - python setup.py install
script: python setup.py test
after_success:
  - coveralls
